# -*- coding: utf-8 -*-
"""mission_control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSp3G0eK1wL05hvCD_NiGlyJ9_8DlHNn
"""

# ===============================================
# MISSION CONTROL AI
# Sistema Inteligente de Monitoramento Espacial
# ===============================================

missao = "Space Guardian"
equipe = "Data Stars"

dados_missao = [
    [23, 91, 88, 97, 90],
    [27, 82, 75, 94, 84],
    [32, 64, 55, 91, 72],
    [42, 20, 12, 70, 25],
    [34, 55, 45, 88, 60],
    [25, 86, 80, 95, 88]
]

areas_monitoradas = [
    "Temperatura interna",
    "Comunicação com a base",
    "Sistema de energia",
    "Suporte de oxigênio",
    "Estabilidade operacional"
]


def analisar_temperatura(valor):
    if valor > 35:
        return "CRÍTICO", 2, "Risco de superaquecimento"
    elif valor < 18 or valor > 30:
        return "ATENÇÃO", 1, "Temperatura fora do ideal"
    else:
        return "NORMAL", 0, "Temperatura estável"


def analisar_comunicacao(valor):
    if valor < 30:
        return "CRÍTICO", 2, "Falha grave na comunicação"
    elif valor < 60:
        return "ATENÇÃO", 1, "Comunicação instável"
    else:
        return "NORMAL", 0, "Comunicação funcionando"


def analisar_bateria(valor):
    if valor < 20:
        return "CRÍTICO", 2, "Energia em nível crítico"
    elif valor < 50:
        return "ATENÇÃO", 1, "Bateria abaixo do recomendado"
    else:
        return "NORMAL", 0, "Energia adequada"


def analisar_oxigenio(valor):
    if valor < 80:
        return "CRÍTICO", 2, "Oxigênio em nível crítico"
    elif valor < 90:
        return "ATENÇÃO", 1, "Oxigênio reduzido"
    else:
        return "NORMAL", 0, "Oxigênio adequado"


def analisar_estabilidade(valor):
    if valor < 40:
        return "CRÍTICO", 2, "Sistema instável"
    elif valor < 70:
        return "ATENÇÃO", 1, "Estabilidade reduzida"
    else:
        return "NORMAL", 0, "Operação estável"


def classificar_ciclo(pontos):
    if pontos <= 2:
        return "MISSÃO ESTÁVEL"
    elif pontos <= 5:
        return "MISSÃO EM ATENÇÃO"
    else:
        return "MISSÃO CRÍTICA"


def recomendacao(risco):
    if risco >= 6:
        return "Ativar protocolos de emergência da missão."
    elif risco >= 3:
        return "Monitorar sistemas e preparar recuperação."
    else:
        return "Manter operação normal."


def tendencia(riscos):
    if riscos[-1] > riscos[0]:
        return "A missão apresentou tendência de piora."
    elif riscos[-1] < riscos[0]:
        return "A missão apresentou tendência de melhora."
    else:
        return "A missão permaneceu estável."


def area_afetada(pontos):
    maior = max(pontos)
    return areas_monitoradas[pontos.index(maior)]



riscos = []
risco_area = [0, 0, 0, 0, 0]

print("=" * 60)
print("MISSION CONTROL AI")
print("=" * 60)

print("Missão:", missao)
print("Equipe:", equipe)
print("Quantidade de ciclos:", len(dados_missao))


for numero, ciclo in enumerate(dados_missao):

    print("=" * 60)
    print("CICLO", numero + 1)

    resultados = [
        analisar_temperatura(ciclo[0]),
        analisar_comunicacao(ciclo[1]),
        analisar_bateria(ciclo[2]),
        analisar_oxigenio(ciclo[3]),
        analisar_estabilidade(ciclo[4])
    ]

    risco_total = 0

    for i in range(5):
        print(
            areas_monitoradas[i],
            "|",
            resultados[i][0],
            "|",
            resultados[i][2]
        )

        risco_total += resultados[i][1]
        risco_area[i] += resultados[i][1]

    riscos.append(risco_total)

    print("Pontuação de risco:", risco_total)
    print("Classificação:", classificar_ciclo(risco_total))
    print("Recomendação:", recomendacao(risco_total))


print("=" * 60)
print("RELATÓRIO FINAL DA MISSÃO")
print("=" * 60)

medias = []

for i in range(5):
    soma = 0

    for ciclo in dados_missao:
        soma += ciclo[i]

    medias.append(soma / len(dados_missao))


print("Missão:", missao)
print("Equipe:", equipe)

print("Média temperatura:", round(medias[0],1), "°C")
print("Média comunicação:", round(medias[1],1), "%")
print("Média bateria:", round(medias[2],1), "%")
print("Média oxigênio:", round(medias[3],1), "%")
print("Média estabilidade:", round(medias[4],1), "%")


print("Ciclo mais crítico: Ciclo", riscos.index(max(riscos))+1)
print("Maior pontuação de risco:", max(riscos))

print("Risco médio:", round(sum(riscos)/len(riscos),1))

print()
print("Tendência:")
print(tendencia(riscos))


print()
print("Pontuação acumulada por área:")

for i in range(5):
    print(areas_monitoradas[i],":",risco_area[i],"pontos")


print()
print("Área mais afetada:")
print(area_afetada(risco_area))


print()
print("Classificação final:")

media = sum(riscos)/len(riscos)

if media <= 2:
    print("MISSÃO ESTÁVEL")

elif media <= 5:
    print("MISSÃO EM ATENÇÃO")

else:
    print("MISSÃO CRÍTICA")


print()
print("Conclusão:")
print("A missão enfrentou uma falha crítica durante o ciclo 4, exigindo ações de emergência.")
print("Após as recomendações automáticas do sistema, os recursos foram recuperados.")
print("No último ciclo, a missão voltou para uma condição estável e segura.")